
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: mysql2
  encoding: utf8
  database: inspire_development
  username: root
  password: password
  host: 127.0.0.1
  pool: 5
  timeout: 5000


test:
  adapter: mysql2
  encoding: utf8
  database: inspire_development
  username: root
  password: password
  host: 127.0.0.1



production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: inspire_production
  username: inspire
  password: <%= ENV['INSPIRE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
